# Generated by Django 4.1.1 on 2022-10-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_thread_updated_alter_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['updated']},
        ),
    ]
